import turtle
turtle.forward (100)
turtle.left (120)
turtle.forward (100)
turtle.left (120)
turtle.forward (100)
turtle.penup()
turtle.forward(90)
turtle.pendown()
turtle.forward(100)
turtle.left (90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.penup()
turtle.forward(120)
turtle.pendown()
turtle.penup()
turtle.forward(85)
turtle.pendown()
turtle.circle(50)

turtle.exitonclick()


